### ISSUE TITLE
Feature: cleanup/finally steps at the end of tame execution

### ISSUE THREAD

**Issue by kassybas** [kassybas/tame#28]
Add a stage to a target that runs at the end of the tame execution, after the script and script of parent.

Name: cleanup/finally/?
(These targets would be executed in the reverse sequence of the script execution.)

Use case: setting up database for testing, tearing it down at the end

```
parent-target:
  deps: child-target
  script: parent-script
  cleanup: parent-cleanup-script

child-target:
  deps: child-deps
  script: child-script
  finally: child-cleanup-script
```

Execution sequence:
- child-deps
- child-script
- parent-script
- child-cleanup-script
- parent-cleanup script
